version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-native-camera
    versions:
    - 3.42.0
    - 3.42.1
    - 3.42.2
    - 3.42.3
    - 3.43.0
    - 3.43.1
    - 3.43.2
    - 3.43.3
    - 3.43.5
  - dependency-name: react-navigation
    versions:
    - 4.4.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
